default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]

      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]

      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        stages: [pre-commit]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2
        stages: [pre-commit]

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
      - id: golangci-lint-full
        name: golangci-lint
        args: [./...]
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        files: \.(go|mod|sum)$
        stages: [pre-commit]
      - id: go-test
        name: go test
        entry: go test --cover ./...
        language: system
        pass_filenames: false
        files: \.(go|mod|sum)$
        stages: [pre-push]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
